FROM python:3.11-slim-bullseye
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
RUN mkdir -p /app/templates_files

# Папка с БД и шаблонами монтируются как том
VOLUME ["/app/app.db", "/app/templates_files"]

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
